services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${CONFIG_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /media:/media
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ${CONFIG_PATH}/mosquitto/config:/mosquitto/config
      - ${CONFIG_PATH}/mosquitto/data:/mosquitto/data
      - ${CONFIG_PATH}/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - 1883:1883/tcp
  voipstatus:
    container_name: voipstatus
    image: stuartfreeman/voipstatus
    restart: unless-stopped
    environment:
      - SPAHOST=spa2102
      - SPAUSER=user
      - SPAPASS
      - MHOST=mqtt
      - MUSER=homeassistant
      - MPASS
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver
    volumes:
      - ${CONFIG_PATH}/lms/config:/config:rw
      - /media:/music:ro
      - ${CONFIG_PATH}/lms/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    restart: unless-stopped
  esphome:
    container_name: esphome
    image: esphome/esphome
    command: dashboard --username admin --password ${ESP_PASS} /config
    volumes:
      - ${CONFIG_PATH}/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  matter:
    container_name: matter
    image: ghcr.io/matter-js/python-matter-server:stable
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${CONFIG_PATH}/matter-server/data:/data/
      - /run/dbus:/run/dbus:ro
  music-assistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant
    restart: unless-stopped
    # Network mode must be set to host for MA to discover and stream to players
    network_mode: host
    volumes:
      - ${CONFIG_PATH}/music-assistant/data:/data/
      # Optional: expose local music to MA by bind-mounting it read-only
      - /media:/media:ro
    environment:
      - LOG_LEVEL=info
  ytdlp-tokens:
    image: brainicism/bgutil-ytdlp-pot-provider
    ports:
      - 4416:4416/tcp
